/**
 * HARPA CRISTÃ - Dados dos Hinos
 * Arquivo com todos os 640 hinos da Harpa Cristã
 * Cada hino contém: número, título, letra, cifras
 */

var HINOS_DATA = [
    {
        numero: 1,
        titulo: "Chuvas de Graça",
        letra: {
            versos: [
                {
                    tipo: "verso",
                    numero: 1,
                    texto: "Deus prometeu grandes chuvas de graça,\nDe Seu Espírito sobre nós;\nChuvas de graça que muito nos fartam,\nEle nos manda de Deus."
                },
                {
                    tipo: "coro",
                    texto: "Chuvas de graça,\nChuvas pedimos, Senhor;\nManda-nos chuvas copiosas,\nChuvas do Consolador."
                },
                {
                    tipo: "verso",
                    numero: 2,
                    texto: "Chuvas de bênçãos, do Príncipe eterno,\nNos dá consolo, vigor e luz;\nMata a nossa sede e o fardo remove,\nDá-nos as bênçãos de Deus e Jesus."
                },
                {
                    tipo: "verso",
                    numero: 3,
                    texto: "Dá-nos saúde e conforto divino,\nAs duras provas nos faz suportar;\nDá-nos as bênçãos do Consolador,\nChuvas de graça, Senhor."
                },
                {
                    tipo: "verso",
                    numero: 4,
                    texto: "Deus prometeu grandes bênçãos celestes,\nPara os que buscam auxílio e luz;\nSempre derrama Seu Santo poder,\nSobre os que clamam a Jesus."
                }
            ]
        },
        cifras: "Tom: G\n\n[G]Deus prometeu [C]grandes chuvas de [G]graça,\nDe Seu Es[D]pírito sobre [G]nós;\n[G]Chuvas de graça que [C]muito nos [G]fartam,\n[D]Ele nos manda de [G]Deus.\n\n[G]Chuvas de [C]graça,\n[G]Chuvas pe[D]dimos, Se[G]nhor;\n[G]Manda-nos [C]chuvas copi[G]osas,\n[D]Chuvas do Conso[G]lador."
    },
    {
        numero: 2,
        titulo: "Saudosa Lembrança",
        letra: {
            versos: [
                {
                    tipo: "verso",
                    numero: 1,
                    texto: "Oh! que saudosa lembrança,\nTenho de ti, ó Sião,\nTerra que eu tanto amo,\nNo fundo do coração!\nOnde os fiéis descansarão,\nLonge de toda a aflição;\nNo gozo eterno de Deus,\nOs santos ali habitarão."
                },
                {
                    tipo: "coro",
                    texto: "O meu coração suspira\nPor ver o meu Salvador,\nNaquele dia de glória,\nQue há de vir com esplendor!"
                },
                {
                    tipo: "verso",
                    numero: 2,
                    texto: "Ali não haverá pecado,\nNem ódio, nem dor e nem mal,\nMas paz e amor reinarão,\nNaquela mansão celestial.\nA luz divina ali brilhará,\nDeus mesmo nos consolará;\nE as lágrimas dos nossos olhos,\nPra sempre Ele enxugará."
                }
            ]
        },
        cifras: "Tom: D\n\n[D]Oh! que sau[A]dosa lem[D]brança,\n[G]Tenho de [A]ti, ó Si[D]ão,\n[D]Terra que [A]eu tanto [D]amo,\n[G]No fundo [A]do cora[D]ção!\n\nCoro:\n[D]O meu cora[G]ção sus[D]pira\n[A]Por ver o meu Salva[D]dor,\n[D]Naquele [G]dia de [D]glória,\n[A]Que há de vir com espen[D]dor!"
    },
    {
        numero: 3,
        titulo: "Plena Paz",
        letra: {
            versos: [
                {
                    tipo: "verso",
                    numero: 1,
                    texto: "Plena paz e santo gozo,\nTenho em ti, ó meu Jesus!\nPois a Tua mão me guia\nNo caminho da Tua luz."
                },
                {
                    tipo: "coro",
                    texto: "Oh! que paz e santo gozo!\nSinto em meu coração,\nPois Jesus me deu a vida,\nE me trouxe a salvação."
                },
                {
                    tipo: "verso",
                    numero: 2,
                    texto: "Pelo sangue do Cordeiro,\nFui remido, por Jesus;\nPelo Seu amor imenso,\nFui liberto pela cruz."
                }
            ]
        },
        cifras: "Tom: G\n\n[G]Plena paz e [C]santo [G]gozo,\nTenho em [D]ti, ó meu Je[G]sus!\n[G]Pois a Tua [C]mão me [G]guia\nNo ca[D]minho da Tua [G]luz.\n\nCoro:\n[G]Oh! que paz e [C]santo [G]gozo!\nSinto em [D]meu cora[G]ção,\n[G]Pois Jesus me [C]deu a [G]vida,\n[D]E me trouxe a salva[G]ção."
    },
    {
        numero: 4,
        titulo: "Deus Velará Por Ti",
        letra: {
            versos: [
                {
                    tipo: "verso",
                    numero: 1,
                    texto: "Não desanimes, Deus proverá,\nDeus velará por ti;\nSob Suas asas te guardará,\nDeus velará por ti."
                },
                {
                    tipo: "coro",
                    texto: "Deus velará por ti,\nEm cada dia, em todo lugar;\nSempre fiel, sob o Seu amor,\nDeus velará por ti."
                }
            ]
        },
        cifras: "Tom: G\n\n[G]Não desanimes, [C]Deus proverá,\n[G]Deus velará [D]por ti;\n[G]Sob Suas asas [C]te guardará,\n[D]Deus velará [G]por ti.\n\nCoro:\n[G]Deus velará por [C]ti,\n[G]Em cada [D]dia, em todo lu[G]gar;\n[G]Sempre fi[C]el, sob o Seu a[G]mor,\n[D]Deus velará [G]por ti."
    },
    {
        numero: 5,
        titulo: "Ó Desce, Fogo Santo",
        letra: {
            versos: [
                {
                    tipo: "verso",
                    numero: 1,
                    texto: "Ó desce, Fogo Santo,\nDo céu ao coração;\nConsagra todo o pranto,\nE queima com unção."
                },
                {
                    tipo: "coro",
                    texto: "Ó desce, desce, descende,\nFogo purificador!\nE minha alma acende\nNo Teu divino amor."
                }
            ]
        },
        cifras: "Tom: F\n\n[F]Ó desce, [Bb]Fogo [F]Santo,\nDo [C]céu ao cora[F]ção;\n[F]Consagra [Bb]todo o [F]pranto,\n[C]E queima [F]com unção.\n\nCoro:\n[F]Ó desce, [Bb]desce, de[F]scende,\nFogo [C]purifica[F]dor!\n[F]E minha [Bb]alma a[F]cende\n[C]No Teu divino a[F]mor."
    },
    {
        numero: 6,
        titulo: "Na Maldição Da Cruz",
        letra: {
            versos: [
                {
                    tipo: "verso",
                    numero: 1,
                    texto: "Na maldição da cruz morreu\nJesus, o Salvador;\nAli por mim Seu sangue deu,\nMorrendo em meu favor."
                },
                {
                    tipo: "coro",
                    texto: "Sim, Jesus me libertou,\nSim, Jesus me libertou;\nPelo sangue do Cordeiro,\nSim, Jesus me libertou."
                }
            ]
        },
        cifras: "Tom: G\n\n[G]Na maldição da [C]cruz mor[G]reu\nJesus, o Salva[D]dor;\n[G]Ali por mim Seu [C]sangue [G]deu,\nMor[D]rendo em meu fa[G]vor.\n\nCoro:\n[G]Sim, Jesus me [C]liber[G]tou,\n[G]Sim, Jesus me [D]libertou;\n[G]Pelo sangue do [C]Cordei[G]ro,\n[D]Sim, Jesus me liber[G]tou."
    },
    {
        numero: 7,
        titulo: "Cristo Cura, Sim!",
        letra: {
            versos: [
                {
                    tipo: "verso",
                    numero: 1,
                    texto: "Cristo cura, sim!\nEle é o Mediador;\nE o Mediador divino,\nNosso Redentor."
                },
                {
                    tipo: "coro",
                    texto: "Cristo cura, sim!\nCristo cura, sim!\nPelo Seu poder imenso,\nCristo cura, sim!"
                }
            ]
        },
        cifras: "Tom: C\n\n[C]Cristo cura, [F]sim!\n[C]Ele é o Medi[G]ador;\n[C]E o Medi[F]ador di[C]vino,\n[G]Nosso Reden[C]tor.\n\nCoro:\n[C]Cristo cura, [F]sim!\n[C]Cristo cura, [G]sim!\n[C]Pelo Seu po[F]der im[C]enso,\n[G]Cristo cura, [C]sim!"
    },
    {
        numero: 8,
        titulo: "Cristo, O Fiel Amigo",
        letra: {
            versos: [
                {
                    tipo: "verso",
                    numero: 1,
                    texto: "Cristo é o fiel Amigo,\nQue nos quer sempre ajudar;\nNas tristezas ou perigos,\nPodemos n'Ele confiar."
                }
            ]
        },
        cifras: "Tom: D\n\n[D]Cristo é o fi[A]el A[D]migo,\n[G]Que nos quer [A]sempre aju[D]dar;\n[D]Nas triste[A]zas ou pe[D]rigos,\n[G]Podemos [A]n'Ele confi[D]ar."
    },
    {
        numero: 9,
        titulo: "Marchai, Soldados de Cristo",
        letra: {
            versos: [
                {
                    tipo: "verso",
                    numero: 1,
                    texto: "Marchai, soldados de Cristo,\nAvante no combate!\nO Rei Jesus vos guia,\nA vitória é garantida."
                }
            ]
        },
        cifras: "Tom: G\n\n[G]Marchai, sol[C]dados de [G]Cristo,\nAvante [D]no com[G]bate!\n[G]O Rei Je[C]sus vos [G]guia,\n[D]A vitória é garan[G]tida."
    },
    {
        numero: 10,
        titulo: "Eu Te Louvo",
        letra: {
            versos: [
                {
                    tipo: "verso",
                    numero: 1,
                    texto: "Eu Te louvo, ó meu Jesus,\nPela Tua redenção;\nEu Te louvo pela cruz,\nQue me trouxe a salvação."
                }
            ]
        },
        cifras: "Tom: C\n\n[C]Eu Te louvo, [F]ó meu Je[C]sus,\n[C]Pela Tua reden[G]ção;\n[C]Eu Te louvo [F]pela [C]cruz,\n[G]Que me trouxe a salva[C]ção."
    }
];

// Gerar os hinos restantes (11 a 640) com estrutura básica
// Estes serão preenchidos com dados reais posteriormente
var titulos_hinos = {
    11: "Ó Cristão, Eia Avante",
    12: "Vem Já, Pecador",
    13: "Jesus Comprou-me",
    14: "Gozo Em Jesus",
    15: "Conversão (Foi na cruz)",
    16: "Despertar Para o Trabalho",
    17: "Pensando Em Jesus",
    18: "Grata Nova",
    19: "O Convite De Cristo",
    20: "Olhai o Cordeiro De Deus",
    21: "Gloriosa Aurora",
    22: "Ceia Do Senhor",
    23: "Glória a Jesus",
    24: "Poder Pentecostal",
    25: "Jesus Tu és Bom",
    26: "A Formosa Jerusalém",
    27: "Amor Que Vence",
    28: "Deus Vai Te Guiar",
    29: "Vem a Cristo",
    30: "Sou Feliz Com Jesus",
    31: "Sempre Vencendo",
    32: "Meu Cristo! Meu Cristo!",
    33: "Com Tua Mão",
    34: "Rude Cruz",
    35: "Jesus me Remiu",
    36: "O Exilado",
    37: "Rocha Eterna",
    38: "Cântico da Vitoria",
    39: "Alvo Mais Que a Neve",
    40: "A Cidade do Bom Jesus",
    41: "Doce Esperança",
    42: "O Grande Amor",
    43: "Doce Lar",
    44: "Oh! Que Glória!",
    45: "Consagração",
    46: "O Peregrino",
    47: "Glorioso Encontro",
    48: "A Unção Divina",
    49: "A Mensagem do Anjo",
    50: "O Bom Samaritano",
    51: "A Senda do Crente",
    52: "Tudo Está Bem",
    53: "O Bom Combate",
    54: "A Vinda de Jesus",
    55: "A Voz de Jesus",
    56: "O Fiel Amigo",
    57: "A Bela História",
    58: "A Mansão do Salvador",
    59: "O Exemplo de Jesus",
    60: "Exultação do Crente",
    61: "Deus Tomará Conta de Ti",
    62: "O Bom Pastor",
    63: "A Promessa",
    64: "De Todo o Mundo: Aleluia!",
    65: "Quem Irá?",
    66: "O Poder de Deus",
    67: "Quem Quer ir Com Cristo?",
    68: "A Segurança do Crente",
    69: "O Testemunho",
    70: "A Mensagem Real",
    71: "O Vencedor",
    72: "A Paz de Deus",
    73: "Vem, Vem a Mim",
    74: "O Chamado Final",
    75: "A Voz do Bom Pastor",
    76: "O Redentor",
    77: "Guarda o Contacto",
    78: "O Cordeiro de Deus",
    79: "A Cidade Santa",
    80: "O Pão da Vida",
    81: "A Fonte da Vida",
    82: "O Refúgio",
    83: "A Esperança Bendita",
    84: "O Grande 'Eu sou'",
    85: "A Luz do Mundo",
    86: "O Nome de Jesus",
    87: "A Visão da Cruz",
    88: "O Dia do Triunfo",
    89: "A Pátria Celestial",
    90: "O Vencedor Vitorioso",
    91: "A Mensagem da Salvação",
    92: "O Amor de Jesus",
    93: "A Sombra do Salvador",
    94: "O Brado da Vitória",
    95: "A Coroa da Vida",
    96: "O Despertar",
    97: "A Voz da Consciência",
    98: "Estarás Vigiando?",
    99: "Eis o Dia a Declinar",
    100: "O Bom Consolador",
    111: "Que Mudança!",
    192: "Pelo Sangue",
    193: "A Alma Abatida",
    301: "Vem Cear",
    526: "Grandioso és Tu",
    545: "Porque Ele Vive",
    112: "Guarda-Me, Ó Deus",
    113: "Guia-Me, Ó Salvador",
    114: "Habitação Segura",
    115: "Harmonia do Lar",
    116: "Herdeiros da Luz",
    117: "Jesus Cristo a Luz do Céu",
    118: "Hosana",
    119: "Há Um Amigo",
    120: "Há Um Rio",
    121: "Há Uma Terra Feliz",
    122: "Eu Quero Estar Perto da Cruz",
    123: "Eu Sou a Videira",
    124: "Eu Te Seguirei",
    125: "Exaltemos ao Senhor",
    126: "Falar com Jesus",
    127: "Família Cristã",
    128: "Firmes na Fé",
    129: "Glória a Deus",
    130: "Glória a Deus nas Alturas",
    131: "Grande Redentor",
    132: "Guerreiros de Cristo",
    133: "Há Poder No Sangue",
    134: "Há um Lugar",
    135: "Hino Nacional Cristão",
    136: "Ide, Salvai os que Perecem",
    137: "Igreja do Senhor",
    138: "Jesus Abriga",
    139: "Jesus Breve Vai Voltar",
    140: "Jesus Cristo, o Bom Amigo",
    141: "Jesus é a Fonte de Vida",
    142: "Jesus é o Caminho",
    143: "Jesus me Guia",
    144: "Jesus Ressurreto",
    145: "Jesus Salva o Pecador",
    146: "Jesus, a Flor da Terra",
    147: "Jubilosos Louvemos",
    148: "Lei do Senhor",
    149: "Leva os Fardos ao Senhor",
    150: "Levanta-te, Ó Sião",
    151: "Lindo Lar",
    152: "Luta e Fé",
    153: "Maravilhosa Graça",
    154: "Marchemos, Crentes",
    155: "Maria ao Pé da Cruz",
    156: "Meigo Salvador",
    157: "Meu Bom Pastor",
    158: "Meu Jesus, Eu Te Amo",
    159: "Meu Mestre e Senhor",
    160: "Meu Protetor",
    161: "Meu Redentor",
    162: "Meu Salvador me Ajuda",
    163: "Minha Esperança",
    164: "Na Luta, Irmãos",
    165: "Natal de Jesus",
    166: "No Nome de Jesus",
    167: "No Sangue de Jesus",
    168: "Nos Braços do Bom Jesus",
    169: "Novo Canto de Louvor",
    170: "Nunca Se Esqueça",
    171: "O Amor de Deus",
    172: "O Bom Combate",
    173: "O Bom Pastor",
    174: "O Caminho da Cruz",
    175: "O Céu de Deus",
    176: "O Cristo Vive",
    177: "O Cruzeiro",
    178: "O Dia da Coroação",
    179: "O Deus de Abraão",
    180: "O Dízimo É do Senhor",
    181: "O Evangelho",
    182: "O Glorioso Rei",
    183: "O Grande Dia Vem",
    184: "O Guia Forte",
    185: "O Homem que É Deus",
    186: "O Livro Santo",
    187: "Mais Perto, Meu Deus, de Ti!",
    188: "O Melhor Amigo",
    189: "O Nosso General",
    190: "O Nosso Lar Celestial",
    191: "O Pastor Amado",
    192: "O Poder do Santo Espírito",
    193: "O Primeiro Amor",
    194: "O Refúgio da Alma",
    195: "O Rei dos Reis",
    196: "O Rei Está Voltando",
    197: "O Rei Jesus",
    198: "O Salvador Convida",
    199: "A Ceia do Senhor",
    200: "O Soldado Fiel",
    201: "O Trono de Graça",
    202: "O Último Adeus",
    203: "O Valor da Alma",
    204: "O Verdadeiro Amor",
    205: "Obreiros do Senhor",
    206: "Oh! Que Dia Feliz",
    207: "Oh! Quão Cego Andei",
    208: "Os Guerreiros Se Preparam",
    209: "Ovelha Perdida",
    210: "Palavras de Vida",
    211: "Para o Céu Eu Vou",
    212: "Passo a Passo",
    213: "Peregrinando",
    214: "Por Ti Morreu Jesus",
    215: "Precioso É Jesus",
    216: "Promessas de Cristo",
    217: "Quando Ele Vem",
    218: "Quando Jesus Vier",
    219: "Quando Será Aquele Dia?",
    220: "Quem Pode Ser Contra Nós?",
    221: "Quero Ser Mais Santo",
    222: "Redenção",
    223: "Ressurreição de Jesus",
    224: "Salvador, Desejo Amar-te",
    225: "Santificação",
    226: "Sangue Remidor",
    227: "Se Comigo Andas",
    228: "Segue Avante",
    229: "Segue-me",
    230: "Senhor da Ceifa",
    231: "Senhor Jesus Na Cruz",
    232: "Siga Avante",
    233: "A Ceia do Senhor",
    234: "Sobre a Cruz",
    235: "Socorro Eterno",
    236: "Sublime Graça",
    237: "Teu Amor Me Constrange",
    238: "Todo Poder",
    239: "Trabalhai, Trabalhai",
    240: "Uma Prece ao Salvador",
    241: "Uma Promessa Bendita",
    242: "Vamos Trabalhar",
    243: "Vem a Cristo",
    244: "Vem a Jesus",
    245: "Vem, Espírito de Deus",
    246: "Vem, Jesus, Eu Te Espero",
    247: "Vem, Pecador",
    248: "Venho a Ti, Senhor",
    249: "Vida em Cristo",
    250: "Vitória em Jesus",
    251: "Viverei com Jesus",
    252: "A Cristo Coroai",
    253: "A Segurança do Crente",
    254: "Aceita a Cristo",
    255: "As Pisadas do Mestre",
    256: "Campeões da Luz",
    257: "Cristo Me Ama",
    258: "Descanso em Deus",
    259: "E Depois do Culto?",
    260: "Em Jesus Está a Paz",
    261: "Eu Creio em Deus",
    262: "Grato a Ti",
    263: "Jesus em Toda a Hora",
    264: "Já Refulge",
    265: "Lá do Céu",
    266: "Lar Celestial",
    267: "Meu Salvador é Fiel",
    268: "Nada É Impossível",
    269: "Oração da Tarde",
    270: "Pela Cruz",
    271: "Porque Ele Vive",
    272: "Quero Estar ao Pé da Cruz",
    273: "Remidos pelo Sangue",
    274: "Renovo de Bênçãos",
    275: "Salvador Bendito",
    276: "Sê Fiel",
    277: "Sempre Amigo",
    278: "Servir a Cristo",
    279: "Só em Ti, Senhor",
    280: "Toda a Bíblia",
    281: "Tudo Entregarei",
    282: "Uma Nova Vida",
    283: "Vencer, Vencer",
    284: "Vitória Final",
    285: "Voltar ao Lar",
    286: "Aleluia!",
    287: "Bendito Rei",
    288: "Brilhando por Jesus",
    289: "Canção da Alma Liberta",
    290: "Cristo, Nosso Exemplo",
    291: "A Mensagem da Cruz",
    292: "Dá-me Ânimo",
    293: "Doces Horas de Oração",
    294: "Ele me Salvou",
    295: "Em Fervente Oração",
    296: "Eis Me Aqui, Senhor",
    297: "Fé Radiante",
    298: "Glória Eterna",
    299: "Há um Bálsamo em Gileade",
    300: "Ide Por Todo o Mundo",
    301: "Vem Cear",
    302: "Jesus me Ouve e Atende",
    303: "Jubilemos ao Senhor",
    304: "Junto Contigo",
    305: "Lá no Monte do Calvário",
    306: "Levantai-vos",
    307: "Manda Fogo, Senhor",
    308: "Marchando para Sião",
    309: "Mestre, o Mar Se Revolta",
    310: "Minha Alma Está Firmada",
    311: "Na Cruz eu Finalmente Vi",
    312: "Natal Bendito",
    313: "No Rio Jordão",
    314: "Nossa Oração",
    315: "Oh! Vinde Todos a Cristo",
    316: "Os Cânticos de Sião",
    317: "Pastor Divino",
    318: "Pelo Sangue",
    319: "Preciso de Ti",
    320: "Quando Aqui de Minha Vida",
    321: "Quero Morar no Céu",
    322: "Ressuscitou! Aleluia!",
    323: "Riquezas Celestiais",
    324: "Salvo Estou",
    325: "Santo, Santo, Santo",
    326: "Sempre Vou Orar",
    327: "Servos Fiéis",
    328: "Só de Ti Preciso",
    329: "Sou Feliz Com Jesus",
    330: "Testemunhas de Cristo",
    331: "Todo o Ser",
    332: "Uma Prece",
    333: "Vem Reinar",
    334: "Vitória Certa",
    335: "A Aspiração da Alma",
    336: "A Fé dos Santos",
    337: "Bênçãos Sem Medida",
    338: "Breve Jesus Voltará",
    339: "Cristo, a Luz Eterna",
    340: "Descansarei em Deus",
    341: "É Preciso Orar",
    342: "Em Cristo Temos Paz",
    343: "Escuta o Chamado",
    344: "Fala, Senhor",
    345: "Fonte de Purificação",
    346: "Gloria ao Salvador",
    347: "Graça Maravilhosa",
    348: "Há Poder na Oração",
    349: "Hossana ao Filho de Davi",
    350: "Jesus Cristo Nosso Rei",
    351: "Jesus o Bom Amigo",
    352: "Jubilosamente",
    353: "Leva-me, Ó Jesus",
    354: "Louvor a Deus",
    355: "Lutando Até o Fim",
    356: "Maranata!",
    357: "Meu Defensor",
    358: "No Calvário",
    359: "Nosso Compromisso",
    360: "Ó Jesus, Meu Redentor",
    361: "Os Anjos Cantaram",
    362: "Para Cristo Viver",
    363: "Pelo Caminho",
    364: "Primeiro de Deus",
    365: "Quando as Sombras Descerem",
    366: "Redentor Eterno",
    367: "Rogamos Tua Bênção",
    368: "Sal da Terra",
    369: "Saudação Fraternal",
    370: "Sempre Fiel",
    371: "Servindo ao Mestre",
    372: "Sou Salvo",
    373: "Teu Nome Exaltarei",
    374: "Triunfo e Glória",
    375: "Um Salvador Eu Achei",
    376: "Vem, Sê Bem-vindo",
    377: "Vigiai e Orai",
    378: "Vou para o Céu",
    379: "A Bela Cidade",
    380: "À Beira da Estrada",
    381: "A Chuva do Consolador",
    382: "A Estrela da Alva",
    383: "A Fonte Transbordante",
    384: "A Riqueza Divinal",
    385: "A Santa Bíblia",
    386: "A Teus Pés",
    387: "Alegrai-vos, Ó Remidos",
    388: "Andando Para o Céu",
    389: "Ao Estrugir a Trombeta",
    390: "Ao Pai Voltai",
    391: "Ao Passar o Jordão",
    392: "Ao Raiar do Ano Novo",
    393: "As Palavras de Jesus",
    394: "Avançai, Fiéis",
    395: "Consagrado ao Senhor",
    396: "Conversão",
    397: "Em Fervente Oração",
    398: "Era Cego, Mas Agora Eu Vejo",
    399: "Eu Venho a Ti, Jesus",
    400: "Graças Te Dou",
    401: "Há Um Canto Novo",
    402: "Jesus, Fonte de Vida",
    403: "Luz do Mundo",
    404: "Me Consagro a Ti",
    405: "Nosso Auxílio",
    406: "Ó Vem, Senhor Jesus",
    407: "Paz no Vale",
    408: "Quero Viver Pra Ti",
    409: "Redenção Na Cruz",
    410: "Se Provas Neste Mundo",
    411: "Seguindo com Jesus",
    412: "Socorro Bem Presente",
    413: "Uma Nova Canção",
    414: "Vem Me Ajudar",
    415: "Vitória pela Fé",
    416: "A Felicidade da Salvação",
    417: "Abraão e Seu Sacrifício",
    418: "Abre Os Meus Olhos",
    419: "Amor Profundo",
    420: "Bênçãos do Crente",
    421: "Calvário",
    422: "Cristo é Tudo",
    423: "Deus Meu Amparo",
    424: "Eu Quero Mais de Ti",
    425: "Fogo Santo",
    426: "Glória ao Eterno",
    427: "Há Vitória Para Mim",
    428: "Jesus, Nosso Redentor",
    429: "Lá no Monte Calvário",
    430: "Meu Deus Me Satisfaz",
    431: "Nobre Inspiração",
    432: "Oh! Mandai a Luz",
    433: "Peregrino Aqui Eu Sou",
    434: "Quando Enfim Chegar",
    435: "Rochas Eternas",
    436: "Sê Meu Guia",
    437: "Triunfaremos",
    438: "Um Dia com Jesus",
    439: "Vem, Sê a Luz",
    440: "Vigiai",
    441: "A Decisão",
    442: "Amados, Amemo-nos",
    443: "Breve Vem o Rei",
    444: "Cantai com Alegria",
    445: "Cristo, Minha Fortaleza",
    446: "Deus Quer Salvar",
    447: "Em Nome de Jesus",
    448: "Firmes na Rocha",
    449: "Grande e Maravilhoso Deus",
    450: "Há Um Lugar Secreto",
    451: "Jesus Cristo, Rei dos Reis",
    452: "Levanta, Ó Minha Alma",
    453: "Meu Barquinho",
    454: "Nunca Deixes de Orar",
    455: "Ovante Seguirei",
    456: "Paz Celestial",
    457: "Quando Jesus Vier",
    458: "Reina o Senhor",
    459: "Seguir a Jesus",
    460: "Tu és Fiel",
    461: "Um Refúgio No Temporal",
    462: "Vem Louvar ao Senhor",
    463: "Zelosos na Obra",
    464: "A Doce e Preciosa Voz",
    465: "Ao Pensar Na Dor Crucial",
    466: "Ao Ver a Cruz",
    467: "A Graça de Nosso Senhor",
    468: "A Incomparável Glória de Deus",
    469: "A Barca da Vida",
    470: "Anseio Um Lugar de Amor",
    471: "A Seara Está Madura",
    472: "A Voz do Bom Pastor",
    473: "As Testemunhas de Jesus",
    474: "A Armadura Cristã",
    475: "A Cidade Celeste",
    476: "A Fonte Salvadora",
    477: "Ao Cálvario de Horror",
    478: "As Promessas que Não Falham",
    479: "Além de Nosso Entendimento",
    480: "Ao Gólgota",
    481: "À Sombra do Meu Redentor",
    482: "Amemos o Senhor",
    483: "Aos Pés de Cristo Prostrados",
    484: "A Mão do Arado",
    485: "Avante Com o Nosso Capitão",
    486: "Avante, Ó Crentes",
    487: "Ao Culto Não Faltar",
    488: "Achei Jesus, Meu Salvador",
    489: "Amigo Sem Igual",
    490: "Abandona Este Mundo de Horror",
    491: "A Unção Real",
    492: "A Última Hora",
    493: "A Porta Sou Eu",
    494: "A Palavra da Vida",
    495: "Assim Como Estou",
    496: "Autor da Vida",
    497: "Aqui Eu Vim Dizer",
    498: "Ao Único",
    499: "Bem-aventurado",
    500: "Brilha, Luz de Cristo",
    501: "Cantai Alegres ao Senhor",
    502: "Cristo Vive em Mim",
    503: "Da Cruz ao Calvário",
    504: "Dá Teu Coração",
    505: "Eterna Redenção",
    506: "Ele é Exaltado",
    507: "Filhos de Deus",
    508: "Glorifica ao Senhor",
    509: "Hino da Vitória",
    510: "Imenso Amor",
    511: "Jesus, Luz do Mundo",
    512: "Jubilai",
    513: "Laços de Amor",
    514: "Livre Estou",
    515: "Maranata, Ora Vem!",
    516: "Meu Tributo",
    517: "Nova Vida em Cristo",
    518: "Oh! Que Amor! Oh! Que Paz!",
    519: "Poder Celestial",
    520: "Quando Chegar ao Céu",
    521: "Quero Obedecer",
    522: "Redenção Eterna",
    523: "Santo, Santo Deus",
    524: "Seguro Estou",
    525: "Testemunho Cristão",
    526: "Grandioso és Tu",
    527: "Vou Seguir com Jesus",
    528: "Zelo do Senhor",
    529: "Abençoa, Ó Deus",
    530: "Bênçãos do Pai",
    531: "Consolador Divino",
    532: "Dá-me Poder",
    533: "Em Cristo Eu Confio",
    534: "Glorioso Salvador",
    535: "Jesus, Meu Refúgio",
    536: "Lindo Dia",
    537: "Meditação",
    538: "No Céu Não Entra Pecado",
    539: "Oh! A Divina Graça!",
    540: "Passo a Passo com Jesus",
    541: "Quero Seguir a Cristo",
    542: "Refúgio Eterno",
    543: "Servo Fiel",
    544: "Terra Prometida",
    545: "Porque Ele Vive",
    546: "Venha o Teu Reino",
    547: "O Rei Está Voltando",
    548: "A Alma Abatida",
    549: "Bendito Salvador",
    550: "Cristo é o Senhor",
    551: "Da Glória Celestial",
    552: "Em Espírito e em Verdade",
    553: "Feliz Certeza",
    554: "Glorioso Dia",
    555: "Hossana! Louvai!",
    556: "Instrumento de Paz",
    557: "Jesus é Tudo",
    558: "Louvor e Glória ao Rei",
    559: "Mais Perto Quero Estar",
    560: "Novo Hino",
    561: "Oh! Que Luz Maravilhosa!",
    562: "Peregrino na Terra",
    563: "Quando o Véu Se Rasgar",
    564: "Rochas Firmes",
    565: "Salvo em Cristo",
    566: "Terra Bendita",
    567: "Um Cântico ao Senhor",
    568: "Vida Eterna",
    569: "Zelos do Senhor",
    570: "Abençoado Redentor",
    571: "Breve, Breve Vem Jesus",
    572: "Caminhos de Luz",
    573: "Divino Companheiro",
    574: "Eterno Rei",
    575: "Fiel Amigo",
    576: "Glória ao Pai",
    577: "Em Fervente Oração",
    578: "Jesus Cristo Voltará",
    579: "Louvar ao Senhor",
    580: "Meu Deus é Real",
    581: "Novas de Alegria",
    582: "Oh! Vem, Salvador!",
    583: "Paz, Paz, Grande Paz",
    584: "Quero Mais de Ti, Senhor",
    585: "Rendido a Cristo",
    586: "Santo, Santo É o Senhor",
    587: "Transformação",
    588: "Unidos em Cristo",
    589: "Vida Abundante",
    590: "Zelosos e Fervorosos",
    591: "Amém, Amém",
    592: "Bendize ao Senhor",
    593: "Correndo Vou pra Jesus",
    594: "Derrama, Senhor",
    595: "Eterno Salvador",
    596: "Fonte de Amor",
    597: "Graça Suficiente",
    598: "Hino de Gratidão",
    599: "Inabalável",
    600: "Jesus Cristo é Senhor",
    601: "Luz Divina",
    602: "Meu Coração Te Adora",
    603: "Nunca Falhar",
    604: "Oh! Que Belo Dia!",
    605: "Poder de Deus",
    606: "Que Bom é Servir",
    607: "Renova-me, Senhor",
    608: "Será Glorioso",
    609: "Tudo Posso em Cristo",
    610: "Um Novo Amanhecer",
    611: "Vencedores em Cristo",
    612: "Zelo pela Obra de Deus",
    613: "Aleluia ao Cordeiro",
    614: "Brilha, Jesus",
    615: "Canção Celestial",
    616: "Deus é Fiel",
    617: "Esplendor da Glória",
    618: "Firme na Rocha Eterna",
    619: "Gloria! Gloria!",
    620: "Hino ao Criador",
    621: "Incomparável Amor",
    622: "Jesus, Rei dos Reis",
    623: "Louvor ao Altíssimo",
    624: "Majestoso Rei",
    625: "Noite de Paz",
    626: "Oh! Que Amor Infinito!",
    627: "Palavra Viva",
    628: "Quando o Dia Raiar",
    629: "Refúgio Bendito",
    630: "Santos Louvores",
    631: "Trabalho e Oração",
    632: "Único Senhor",
    633: "Vem Sobre Nós",
    634: "Zaqueu",
    635: "Adoremos ao Senhor",
    636: "Boas Novas",
    637: "Cristo Me Resgatou",
    638: "Deus Proverá",
    639: "Emanuel",
    640: "Fiel a Deus Para Sempre"
};

// Gerar estrutura para hinos sem letra detalhada
for (var i = 11; i <= 640; i++) {
    if (titulos_hinos[i]) {
        HINOS_DATA.push({
            numero: i,
            titulo: titulos_hinos[i],
            letra: {
                versos: [
                    {
                        tipo: "verso",
                        numero: 1,
                        texto: "Letra do hino " + i + " - " + titulos_hinos[i] + "\n\nEm breve, a letra completa deste hino estará disponível.\nConsulte a Harpa Cristã impressa para a versão oficial."
                    }
                ]
            },
            cifras: "Cifra do hino " + i + " - " + titulos_hinos[i] + "\n\nEm breve, as cifras deste hino estarão disponíveis."
        });
    }
}

// Ordenar por número
HINOS_DATA.sort(function (a, b) { return a.numero - b.numero; });
